name: Sync OpenWrt Repositories

on:
  schedule:
    - cron: '0 20 * * 5'  # 每 6 小时同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]:Jianx"
          git config --global user.email "github-actions[bot]@jianx70687547@gmail.com"

      - name: 1.1Clone OpenWrt Official
        run: git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt

      - name: 1.2Push OpenWrt Official to myrepo
        run: |
          cd openwrt
          git remote add myrepo https://${{ secrets.GH_PAT }}@github.com/JianxSir/WrtSourceAll.git
          git push -f myrepo HEAD:openwrt

      - name: 2.1Clone ImmortalWrt
        run: git clone --depth=1 https://github.com/immortalwrt/immortalwrt.git immortalwrt

      - name: 2.2Push ImmortalWrt Official to myrepo
        run: |
          cd immortalwrt
          git remote add myrepo https://${{ secrets.GH_PAT }}@github.com/JianxSir/WrtSourceAll.git
          git push -f myrepo HEAD:immortalwrt
          
      - name: 3.1Clone Lede
        run: git clone --depth=1 https://github.com/coolsnowwolf/lede.git lede

      - name: 3.2Push Lede to myrepo
        run: |
          cd lede
          git remote add myrepo https://${{ secrets.GH_PAT }}@github.com/JianxSir/WrtSourceAll.git
          git push -f myrepo HEAD:lede
          
      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]:Jianx"
          git config --global user.email "github-actions[bot]@jianx70687547@gmail.com"
          git remote set-url myrepo https://${{ secrets.GH_PAT }}@github.com/JianxSir/WrtSourceAll.git
